---
- name: APT | Update
  apt: update_cache=yes cache_valid_time=3600

- name: APT | Install few packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_flattened:
    - "{{ packages }}"
