---
- name: HOSTNAME
  hostname: name={{ inventory_hostname }}
  notify: restart rsyslog
  register: change_hostname

- name: TEMPLATE | Cleanup /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts
  notify: restart rsyslog

- name: SERVICE | Force networking restart
  service: name=networking state=restarted
  when: change_hostname.changed
