---
- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - system-config
    - leds

- hosts: localhost
  roles:
    - cfssl-kubernetes

- hosts: etcd-nodes
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - etcd

- hosts: kube-controllers
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - kube-controller

- hosts: kube-minions
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - kube-minion
