---
- name: restart openntpd
  service: name=openntpd state=restarted

- name: restart ntp
  service: name=ntp state=restarted

- name: locale-gen
  command: locale-gen

- name: reload networking
  service: name=networking state=reloaded

- name: Reboot Server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: yes
  become_method: sudo
  ignore_errors: true

- name: Waiting for server to come back
  local_action: wait_for port=22 host="{{ ansible_ssh_host }}"  search_regex=OpenSSH delay=10
  become: no
